/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.DBConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WILLROSS
 */
public class Incremento extends javax.swing.JFrame {

    Connection con;

    Statement st;
    ResultSet rs;

    DefaultTableModel tabla;

    int idc;

    /**
     * Creates new form Incremento
     */
    public Incremento() {
        initComponents();
        consulta();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        CANTIDAD = new javax.swing.JTextField();
        MONTO = new javax.swing.JTextField();
        regresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CANTIDAD2 = new javax.swing.JTextField();
        MONTO2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        STOCKMAX = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Incrementar = new javax.swing.JButton();
        Calculadora = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Repuestos2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENRARIO DE REPUESTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 43));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CODIGO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MONTO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INCREMENTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 40));

        CODIGO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODIGOActionPerformed(evt);
            }
        });
        CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CODIGOKeyTyped(evt);
            }
        });
        jPanel1.add(CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 220, 40));

        NOMBRE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBREActionPerformed(evt);
            }
        });
        NOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NOMBREKeyTyped(evt);
            }
        });
        jPanel1.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 40));

        CANTIDAD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CANTIDAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CANTIDADKeyTyped(evt);
            }
        });
        jPanel1.add(CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 40));

        MONTO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MONTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MONTOKeyTyped(evt);
            }
        });
        jPanel1.add(MONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 220, 40));

        regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CANTIDAD INCREMENTAR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 260, 40));

        CANTIDAD2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CANTIDAD2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CANTIDAD2KeyTyped(evt);
            }
        });
        jPanel1.add(CANTIDAD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 220, 40));

        MONTO2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MONTO2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MONTO2KeyTyped(evt);
            }
        });
        jPanel1.add(MONTO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 220, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MONTO INCREMENTAR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 230, 40));

        STOCKMAX.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        STOCKMAX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                STOCKMAXKeyTyped(evt);
            }
        });
        jPanel1.add(STOCKMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 220, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STOCK MAX");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 130, 40));

        Incrementar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Incrementar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incremento.png"))); // NOI18N
        Incrementar.setText("IMCREMENTAR ");
        Incrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncrementarActionPerformed(evt);
            }
        });
        jPanel1.add(Incrementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        Calculadora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora.png"))); // NOI18N
        Calculadora.setText("CALCULADORA");
        Calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraActionPerformed(evt);
            }
        });
        jPanel1.add(Calculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, 40));

        Repuestos2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Repuestos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "CATEGORIA", "MONTO", "IMPUESTO", "STOCK MAX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Repuestos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Repuestos2.setDropMode(javax.swing.DropMode.ON_OR_INSERT_COLS);
        Repuestos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Repuestos2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Repuestos2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 630, 300));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODIGOActionPerformed

    private void CODIGOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODIGOKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_CODIGOKeyTyped

    private void NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBREActionPerformed

    private void NOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOMBREKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            if (!Character.isWhitespace(c) || c == java.awt.event.KeyEvent.VK_ENTER) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_NOMBREKeyTyped

    private void CANTIDADKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CANTIDADKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_CANTIDADKeyTyped

    private void MONTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MONTOKeyTyped
        char c = evt.getKeyChar();
        String text = ((javax.swing.text.JTextComponent) evt.getSource()).getText();
        if (!Character.isDigit(c) && c != '.' && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            return;
        }
        if (c == '.' && text.contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_MONTOKeyTyped

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Menu m = new Menu();
        m.show();
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void Repuestos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repuestos2MouseClicked
        int fila = Repuestos2.getSelectedRow();

        if (fila != -1) {
            try {

                String codigo = String.valueOf(Repuestos2.getValueAt(fila, 0));
                String nombre = String.valueOf(Repuestos2.getValueAt(fila, 1));
                String cantidad = String.valueOf(Repuestos2.getValueAt(fila, 2));

                String precio = String.valueOf(Repuestos2.getValueAt(fila, 4));
                String StockMax = String.valueOf(Repuestos2.getValueAt(fila, 6));

                int id = Integer.parseInt(codigo);
                int cant = Integer.parseInt(cantidad);
                float mon = Float.parseFloat(precio);
                int stmx = Integer.parseInt(StockMax);

                CODIGO.setText(String.valueOf(id));
                NOMBRE.setText(nombre);
                CANTIDAD.setText(String.valueOf(cant));
                MONTO.setText(String.valueOf(mon));
                STOCKMAX.setText(String.valueOf(stmx));

            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Error: El formato de los datos numéricos es incorrecto.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Ha ocurrido un error inesperado al cargar los datos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null,
                    "Por favor, seleccione una fila de la tabla para cargar los datos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Repuestos2MouseClicked

    private void CANTIDAD2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CANTIDAD2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_CANTIDAD2KeyTyped

    private void MONTO2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MONTO2KeyTyped
        char c = evt.getKeyChar();
        String text = ((javax.swing.text.JTextComponent) evt.getSource()).getText();
        if (!Character.isDigit(c) && c != '.' && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            return;
        }
        if (c == '.' && text.contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_MONTO2KeyTyped

    private void IncrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementarActionPerformed
        String codigo = this.CODIGO.getText();
        String cantidad = this.CANTIDAD2.getText();
        String stockMax = this.STOCKMAX.getText();
        String monto = this.MONTO2.getText();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, Seleccione los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cantidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad a incrementar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (monto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el monto a incrementar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int nuevaCantidad;
        float nuevoMonto;
        int stockMaximo;
        try {
            nuevaCantidad = Integer.parseInt(cantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada no es un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            nuevoMonto = Float.parseFloat(monto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El monto ingresado no es un número decimal válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            stockMaximo = Integer.parseInt(stockMax);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El Stock Máximo no es un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nuevaCantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad a incrementar debe ser mayor que cero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;
        PreparedStatement psSelect = null;
        PreparedStatement psUpdate = null;
        ResultSet rs = null;

        try {
            con = DBConexion.conectar();
            boolean encontrado = false;

            String selectQuery = "SELECT cantidad, precio FROM repuestos WHERE codigo = ?";
            psSelect = con.prepareStatement(selectQuery);
            psSelect.setString(1, codigo);
            rs = psSelect.executeQuery();

            if (rs.next()) {
                encontrado = true;
                int cantidadActual = rs.getInt("cantidad");
                float montoActual = rs.getFloat("precio");

                int cantidadFinal = cantidadActual + nuevaCantidad;

                if (cantidadFinal > stockMaximo) {

                    JOptionPane.showMessageDialog(
                            null,
                            "No se puede incrementar la cantidad. El Stock Máximo es de " + stockMaximo + " y la cantidad resultante sería " + cantidadFinal + ".",
                            "Límite",
                            JOptionPane.WARNING_MESSAGE
                    );

                    return;
                }

                float montoFinal = montoActual + nuevoMonto;

                String updateQuery = "UPDATE repuestos SET cantidad = ?, precio = ? WHERE codigo = ?";
                psUpdate = con.prepareStatement(updateQuery);
                psUpdate.setInt(1, cantidadFinal);
                psUpdate.setFloat(2, montoFinal);
                psUpdate.setString(3, codigo);

                int filasAfectadas = psUpdate.executeUpdate();

                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(null, "Cantidad y monto actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    this.CANTIDAD.setText(String.valueOf(cantidadFinal));
                    this.MONTO.setText(String.valueOf(montoFinal));
                    this.CANTIDAD2.setText("");
                    this.MONTO2.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(null, "El repuesto con código " + codigo + " no está registrado.", "Repuesto No Encontrado", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error de base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (psSelect != null) {
                    psSelect.close();
                }
                if (psUpdate != null) {
                    psUpdate.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                System.err.println("Error al cerrar recursos de BD: " + e.getMessage());
            }
        }

        limpiartabla();
        consulta();
        Limpiar();

    }//GEN-LAST:event_IncrementarActionPerformed

    private void STOCKMAXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_STOCKMAXKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_STOCKMAXKeyTyped

    private void CalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraActionPerformed
        Calculadora c = new Calculadora();
        c.setVisible(true);

    }//GEN-LAST:event_CalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incremento().setVisible(true);
            }
        });
    }

    public void consulta() {
        String sql = "select * from repuestos";

        try {
            Connection con = DBConexion.conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] Repuestos = new Object[10];
            tabla = (DefaultTableModel) Repuestos2.getModel();

            while (rs.next()) {
                Repuestos[0] = rs.getInt("codigo");
                Repuestos[1] = rs.getString("nombre");
                Repuestos[2] = rs.getInt("cantidad");
                Repuestos[3] = rs.getString("categoria");
                Repuestos[4] = rs.getFloat("precio");
                Repuestos[5] = rs.getFloat("impuesto");
                Repuestos[6] = rs.getInt("stock_maximo");

                tabla.addRow(Repuestos);

            }
            Repuestos2.setModel(tabla);

        } catch (SQLException e) {
            e.printStackTrace();
            {
            }

        }
    }

    public void limpiartabla() {

        DefaultTableModel modelo = (DefaultTableModel) Repuestos2.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

    }

    public void Limpiar() {
        CODIGO.setText("");
        NOMBRE.setText("");
        CANTIDAD.setText("");
        MONTO.setText("");
        CANTIDAD2.setText("");
        MONTO2.setText("");
        STOCKMAX.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JTextField CANTIDAD2;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JButton Calculadora;
    private javax.swing.JButton Incrementar;
    private javax.swing.JTextField MONTO;
    private javax.swing.JTextField MONTO2;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTable Repuestos2;
    private javax.swing.JTextField STOCKMAX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
