package Formularios;

import Clases.DBConexion;
import Clases.Hash;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * * @author WILLROSS
 *
 *
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Loginn
     */
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
 this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        login = new javax.swing.JTextField();
        Login = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        acceder = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        unlock = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 218, 220, 40));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        rol.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        rol.setForeground(new java.awt.Color(255, 255, 255));
        rol.setText("User-Admin");
        getContentPane().add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 40));

        Contraseña.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, -1));

        acceder.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acceso.png"))); // NOI18N
        acceder.setText("Acceder  ");
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });
        getContentPane().add(acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 160, -1));

        salir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 115, -1));

        unlock.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        unlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desbloquear.png"))); // NOI18N
        unlock.setText("Unlock");
        unlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockActionPerformed(evt);
            }
        });
        getContentPane().add(unlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 40));

        registrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userr.png"))); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        pass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 318, 220, 40));

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 530));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        int X = JOptionPane.showConfirmDialog(null, "¿Deseas salir del sistema?", "Cerrar Sistema", JOptionPane.YES_NO_OPTION);
        if (X == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            pass.setEchoChar((char) 0);
        } else {
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void unlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockActionPerformed
        String a = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese la contraseña maestra",
                "Activar",
                JOptionPane.QUESTION_MESSAGE,
                null,
                null,
                ""
        );
        if (a != null) {
            if (a.trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "El campo no puede estar vacío.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
            } else if (a.equals("32138367")) {
                this.acceder.setEnabled(true);
                this.salir.setEnabled(true);
                this.registrar.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Contraseña correcta.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "La contraseña es incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_unlockActionPerformed
    int intentos = 3;
    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
        String Usser = this.login.getText();
        String PassPlana = new String(this.pass.getPassword());

        if (Usser.isEmpty() || PassPlana.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe llenar ambos campos de User-Admin y Contraseña.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        String query = "SELECT Contraseña, Rol FROM login WHERE Usuario = ?";

        try {
            con = DBConexion.conectar();
            ps = con.prepareStatement(query);
            ps.setString(1, Usser);
            rs = ps.executeQuery();

            boolean loginExitoso = false;

            if (rs.next()) {
                String hashDB = rs.getString("Contraseña");
                String rolDB = rs.getString("Rol");

                if (Hash.verificarContrasena(PassPlana, hashDB)) {

                    loginExitoso = true;

                    if (rolDB.equals("Administrador")) {
                        Menu m = new Menu();
                        m.show();
                        dispose();
                    } else if (rolDB.equals("Usuario")) {
                        MenuU mu = new MenuU();
                        mu.show();
                        dispose();
                    }

                    intentos = 3;

                    return;
                }
            }

            if (!loginExitoso) {

                intentos--;

                if (intentos > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Datos incorrectos. Le quedan " + intentos + " intentos.",
                            "Error de Acceso",
                            JOptionPane.ERROR_MESSAGE);
                } else {

                    JOptionPane.showMessageDialog(this,
                            "Se agotaron los 3 intentos. El sistema se ha bloqueado.",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);

                    this.acceder.setEnabled(false);
                    this.salir.setEnabled(false);
                    this.registrar.setEnabled(false);

                    this.login.setText("");
                    this.pass.setText("");
                    JOptionPane.showMessageDialog(this,
                            "Precione Unlock.",
                            "Informacion",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "❌ Error al conectar o ejecutar la consulta: " + e.getMessage(), "Error de Sistema", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {

            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                System.err.println("Error al cerrar recursos: " + ex.getMessage());
            }
        }


    }//GEN-LAST:event_accederActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        String a = (String) JOptionPane.showInputDialog(
                null,
                "Ingrese la contraseña",
                "Registrar User-Admin",
                JOptionPane.QUESTION_MESSAGE,
                null,
                null,
                ""
        );

        if (a != null) {

            if (a.trim().isEmpty()) {

                JOptionPane.showMessageDialog(
                        null,
                        "El campo no puede estar vacío.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );

            } else if (a.equals("32113024")) {

                Registrar_Admin ra = new Registrar_Admin();
                ra.show();
                this.setVisible(false);

            } else {

                JOptionPane.showMessageDialog(null, "La contraseña es incorrecta", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_registrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Login;
    private javax.swing.JButton acceder;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel rol;
    private javax.swing.JButton salir;
    private javax.swing.JButton unlock;
    // End of variables declaration//GEN-END:variables
}
