/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.DBConexion;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author WILLROSS
 */
public class Operaciones extends javax.swing.JFrame {

    Connection con;

    Statement st;
    ResultSet rs;

    DefaultTableModel Tabla;

    int idc;

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        consulta();
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CODIGO = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        CATEGORIA = new javax.swing.JTextField();
        PRECIO = new javax.swing.JTextField();
        IMPUESTO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Compras = new javax.swing.JTable();
        regresar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CODIGO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CODIGOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CODIGOKeyTyped(evt);
            }
        });
        jPanel1.add(CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 220, 40));

        NOMBRE.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NOMBREKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NOMBREKeyTyped(evt);
            }
        });
        jPanel1.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 220, 40));

        CATEGORIA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(CATEGORIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 220, 40));

        PRECIO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PRECIO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PRECIOKeyTyped(evt);
            }
        });
        jPanel1.add(PRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 220, 40));

        IMPUESTO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        IMPUESTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMPUESTOKeyTyped(evt);
            }
        });
        jPanel1.add(IMPUESTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 220, 40));

        Compras.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CATEGORIA", "PRECIO", "IMPUESTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Compras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 300));

        regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, -1));

        buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        actualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        actualizar.setText("ACTUALIZAR PRECIO");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 210, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUEVO IMPUESTO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NUEVO PRECIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CATEGORIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CODIGO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OPERACIONES DE COMPRAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Menu m = new Menu();
        m.show();
        dispose();

    }//GEN-LAST:event_regresarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:

        String codigoStr = this.CODIGO.getText().trim();
        String Nombre = this.NOMBRE.getText().trim();
        String categoria = this.CATEGORIA.getText().trim();
        String precioStr = this.PRECIO.getText().trim();
        String impuestoStr = this.IMPUESTO.getText().trim();

        if (codigoStr.isEmpty() || Nombre.isEmpty() || categoria.isEmpty()
                || precioStr.isEmpty() || impuestoStr.isEmpty()) {

            JOptionPane.showMessageDialog(null, "❌ Es necesario llenar todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "UPDATE repuestos SET nombre=?, categoria=?, precio=?, impuesto=? WHERE codigo=?";

        try {

            int codigo = Integer.parseInt(codigoStr);
            float precio = Float.parseFloat(precioStr);
            float impuesto = Float.parseFloat(impuestoStr);

            Connection con = DBConexion.conectar();
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, Nombre);
            ps.setString(2, categoria);
            ps.setFloat(3, precio);
            ps.setFloat(4, impuesto);

            ps.setInt(5, codigo);

            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "✅ Datos actualizados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se encontró el repuesto con el código proporcionado (" + codigo + ").");
            }

            limpiartabla();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                    "❌ Asegúrese de que Código sea un entero, y Precio e Impuesto sean números válidos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "❌ Error al actualizar los datos en la base de datos: " + e.getMessage());
        }

        limpiartabla();
        consulta();
        limpiar();

    }//GEN-LAST:event_actualizarActionPerformed

    private void CODIGOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODIGOKeyReleased

    }//GEN-LAST:event_CODIGOKeyReleased

    private void NOMBREKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOMBREKeyReleased
        String CriterioBusqueda = this.NOMBRE.getText().trim();

        String expresionRegEx = "(?i)" + Pattern.quote(CriterioBusqueda);

        DefaultTableModel ModeloObtenido = (DefaultTableModel) Compras.getModel();
        TableRowSorter<DefaultTableModel> ordenador = new TableRowSorter<>(ModeloObtenido);

        Compras.setRowSorter(ordenador);

        ordenador.setRowFilter(RowFilter.regexFilter(expresionRegEx, 1));
    }//GEN-LAST:event_NOMBREKeyReleased

    private void ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasMouseClicked

        int fila = Compras.getSelectedRow();

        if (fila != -1) {
            try {

                String codigoStr = String.valueOf(Compras.getValueAt(fila, 0));
                String Nombre = String.valueOf(Compras.getValueAt(fila, 1));
                String precioStr = String.valueOf(Compras.getValueAt(fila, 3));
                String categoria = String.valueOf(Compras.getValueAt(fila, 2));
                String impuestoStr = String.valueOf(Compras.getValueAt(fila, 4));

                int id = Integer.parseInt(codigoStr);
                float pre = Float.parseFloat(precioStr);
                float imp = Float.parseFloat(impuestoStr);

                CODIGO.setText(String.valueOf(id));
                NOMBRE.setText(Nombre);
                CATEGORIA.setText(categoria);
                PRECIO.setText(String.valueOf(pre));
                IMPUESTO.setText(String.valueOf(imp));

            } catch (NumberFormatException e) {
                e.printStackTrace();

                JOptionPane.showMessageDialog(null,
                        "Error de formato: El valor '" + "' no es un número. Revise el orden de sus columnas.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Ha ocurrido un error inesperado al cargar los datos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Por favor, seleccione una fila de la tabla para cargar los datos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_ComprasMouseClicked

    private void PRECIOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PRECIOKeyTyped
        char c = evt.getKeyChar();
        String text = ((javax.swing.text.JTextComponent) evt.getSource()).getText();
        if (!Character.isDigit(c) && c != '.' && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            return;
        }
        if (c == '.' && text.contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_PRECIOKeyTyped

    private void IMPUESTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMPUESTOKeyTyped
        char c = evt.getKeyChar();
        String text = ((javax.swing.text.JTextComponent) evt.getSource()).getText();
        if (!Character.isDigit(c) && c != '.' && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            return;
        }
        if (c == '.' && text.contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_IMPUESTOKeyTyped

    private void NOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOMBREKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            if (!Character.isWhitespace(c) || c == java.awt.event.KeyEvent.VK_ENTER) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_NOMBREKeyTyped

    private void CODIGOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODIGOKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_CODIGOKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        int encontrado = 0;
        String query = "select * from repuestos";
        String a = this.CODIGO.getText();

        try {
            Connection con = DBConexion.conectar();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {

                if (rs.getString(1).equals(a)) {

                    this.NOMBRE.setText(rs.getString(2));
                    this.CATEGORIA.setText(rs.getString(4));
                    this.PRECIO.setText(rs.getString(5));
                    this.IMPUESTO.setText(rs.getString(6));

                    encontrado = 1;
                    break;

                }

            }

            if (encontrado == 1) {

            } else {

                JOptionPane.showMessageDialog(null, "El repuesto no esta registrado.");

            }

            rs.close();
            st.close();
            con.close();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error de base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    public void consulta() {
        String sql = "select * from repuestos";

        try {
            Connection con = DBConexion.conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] Repuestos = new Object[10];
            Tabla = (DefaultTableModel) Compras.getModel();

            while (rs.next()) {
                Repuestos[0] = rs.getInt("codigo");
                Repuestos[1] = rs.getString("nombre");
                Repuestos[2] = rs.getString("categoria");
                Repuestos[3] = rs.getFloat("precio");
                Repuestos[4] = rs.getFloat("impuesto");

                Tabla.addRow(Repuestos);

            }
            Compras.setModel(Tabla);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void limpiartabla() {

        DefaultTableModel modelo = (DefaultTableModel) Compras.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);

        }

    }

    public void limpiar() {

        this.CATEGORIA.setText("");
        this.CODIGO.setText("");
        this.IMPUESTO.setText("");
        this.PRECIO.setText("");
        this.NOMBRE.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CATEGORIA;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTable Compras;
    private javax.swing.JTextField IMPUESTO;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField PRECIO;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
