package Formularios;

import Clases.Conexion;
import Clases.DBConexion;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author WILLROSS
 */
public class Proveedores extends javax.swing.JFrame {

    int idc;

    Statement st;
    ResultSet rs;

    Connection con;

    DefaultTableModel Tabla1;

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        consulta();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RIF = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        CORREO = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JTextField();
        DIRECCION = new javax.swing.JTextField();
        STATUS = new javax.swing.JTextField();
        regresar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Proveedores = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RIF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(RIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, -1));

        NOMBRE.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, -1));

        CORREO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(CORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 250, -1));

        TELEFONO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 250, -1));

        DIRECCION.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 250, -1));

        STATUS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 250, -1));

        regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, -1));

        limpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CORREO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, 30));

        eliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, -1, -1));

        modificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificar.png"))); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, -1, -1));

        registrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registrar.png"))); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 150, -1));

        Proveedores.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RIF", "NOMBRE", "TELEFONO", "DIRECCION", "CORREO", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Proveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1000, 270));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STATUS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DIRECCION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELEFONO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RIF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRAR PROVEEDOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        Nuevo();

    }//GEN-LAST:event_limpiarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        int I = JOptionPane.showConfirmDialog(null, "¿Esta seguro de regresar?", "Mensaje", JOptionPane.YES_NO_OPTION);
        if (I == 0) {
            Menu m = new Menu();
            m.show();
            dispose();

        }
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:

        Agregar();
        limpiartabla();
        consulta();
        Nuevo();
    }//GEN-LAST:event_registrarActionPerformed

    private void ProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedoresMouseClicked
        // TODO add your handling code here:

        int fila = Proveedores.getSelectedRow();

        if (fila != -1) {
            try {

                String Rif = String.valueOf(Proveedores.getValueAt(fila, 0));
                String nombre = String.valueOf(Proveedores.getValueAt(fila, 1));
                String telefono = String.valueOf(Proveedores.getValueAt(fila, 2));
                String direccion = String.valueOf(Proveedores.getValueAt(fila, 3));
                String correo = String.valueOf(Proveedores.getValueAt(fila, 4));
                String status = String.valueOf(Proveedores.getValueAt(fila, 5));

                RIF.setText(Rif);
                NOMBRE.setText(nombre);
                TELEFONO.setText(telefono);
                DIRECCION.setText(direccion);
                CORREO.setText(correo);
                STATUS.setText(status);

            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Error: El formato de los datos numéricos es incorrecto (Ej.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Ha ocurrido un error inesperado al cargar los datos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null,
                    "Por favor, seleccione una fila de la tabla para cargar los datos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_ProveedoresMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        Modificado();
        limpiartabla();
        consulta();
        Nuevo();
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
        limpiartabla();
        consulta();
        Nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    void consulta() {
        String sql = "select * from proveedor";

        try {
            Connection con = DBConexion.conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] Pro = new Object[6];
            Tabla1 = (DefaultTableModel) Proveedores.getModel();

            while (rs.next()) {
                Pro[0] = rs.getString("rif");
                Pro[1] = rs.getString("nombre");
                Pro[2] = rs.getString("telefono");
                Pro[3] = rs.getString("direccion");
                Pro[4] = rs.getString("correo");
                Pro[5] = rs.getString("status");

                Tabla1.addRow(Pro);

            }
            Proveedores.setModel(Tabla1);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    void Agregar() {

        String rif = this.RIF.getText();
        String nombre = this.NOMBRE.getText();
        String Direccion = this.TELEFONO.getText();
        String Correo = this.DIRECCION.getText();
        String telefono = this.CORREO.getText();
        String status = this.STATUS.getText();

        String Query = "INSERT INTO Proveedor (rif,nombre,telefono,direccion,correo,status) VALUES (?,?,?,?,?,?)";

        try {

            Connection con = DBConexion.conectar();
            PreparedStatement ps = con.prepareStatement(Query);

            ps.setString(1, rif);
            ps.setString(2, nombre);
            ps.setString(3, telefono);
            ps.setString(4, Direccion);
            ps.setString(5, Correo);
            ps.setString(6, status);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se ha registrado proveedor con exito!");

        } catch (SQLException e) {
            e.printStackTrace();

        }

    }

    void limpiartabla() {

        for (int i = 0; i < Proveedores.getRowCount(); i++) {
            Tabla1.removeRow(i);

            i = i - 1;

        }

    }

    void Nuevo() {

        this.DIRECCION.setText("");
        this.TELEFONO.setText("");
        this.RIF.setText("");
        this.STATUS.setText("");
        this.CORREO.setText("");
        this.NOMBRE.setText("");
    }

    void Modificado() {

        String rif = this.RIF.getText();
        String nombre = this.NOMBRE.getText();
        String Direccion = this.TELEFONO.getText();
        String Correo = this.DIRECCION.getText();
        String telefono = this.CORREO.getText();
        String status = this.STATUS.getText();

        String Query = "UPDATE proveedor SET nombre=?, telefono=?, direccion=?, correo=?,status=? WHERE RIF=?";

        try {
            Connection con = DBConexion.conectar();
            PreparedStatement ps = con.prepareStatement(Query);

            ps.setString(1, nombre);
            ps.setString(2, Direccion);
            ps.setString(3, Correo);
            ps.setString(4, telefono);
            ps.setString(5, status);
            ps.setString(6, rif); //Dato de referencia del proveedor

            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el código proporcionado");
            }

        } catch (SQLException e) {
            e.printStackTrace();

        }

    }

    void eliminar() {

        int fila = Proveedores.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar.");
            limpiartabla();
            return;
        }

        try {
            int codigoAEliminar = Integer.parseInt(String.valueOf(Proveedores.getValueAt(fila, 0)));

            Connection con = DBConexion.conectar();

            String Query = "DELETE FROM proveedor WHERE rif = ?";
            PreparedStatement ps = con.prepareStatement(Query);

            ps.setInt(1, codigoAEliminar);

            int filasAfectadas = ps.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "El proveedor con código " + codigoAEliminar + " ha sido eliminado.");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el proveedor con el código seleccionado.");
            }

            ps.close();
            con.close();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Error interno: El código del repuesto no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CORREO;
    private javax.swing.JTextField DIRECCION;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTable Proveedores;
    private javax.swing.JTextField RIF;
    private javax.swing.JTextField STATUS;
    private javax.swing.JTextField TELEFONO;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JButton registrar;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
