/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.sql.*;
import Clases.DBConexion;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author WILLROSS
 */
public class Repuestos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Repuestos.class.getName());

    Connection con;

    Statement st;
    ResultSet rs;

    DefaultTableModel tabla;

    int idc;

    /**
     * Creates new form cc
     */
    public Repuestos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Repuesto1 = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, 30));

        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, -1));

        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 170, -1));

        jTextField5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, -1));

        jTextField6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 170, 30));

        jTextField7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 170, -1));

        jTextField8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 170, 30));

        jTextField9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 170, -1));

        jTextField10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 170, -1));

        Repuesto1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Repuesto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "CATEGORIA", "PRECIO", "GANANCIA", "IMPUESTO", "DESCRIPCION", "STOCK MINIMO", "STOCK MAXIMO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Repuesto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Repuesto1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Repuesto1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Repuesto1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1000, 210));

        eliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 150, -1));

        modificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modificar.png"))); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, -1, -1));

        limpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, -1, -1));

        registrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registrar.png"))); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("IMPUESTO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DESCRIPCION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CATEGORIA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 120, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRECIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CANTIDAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOCK MAXIMO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STOCK MINIMO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GANANCIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPUESTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CODIGO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        int I = JOptionPane.showConfirmDialog(null, "¿Esta seguro de regresar?", "Mensaje", JOptionPane.YES_NO_OPTION);
        if (I == 0) {
            Menu m = new Menu();
            m.show();
            dispose();

        }
    }//GEN-LAST:event_regresarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        Registrar();
        limpiartabla();
        consulta();
        limpiarnuevo();
    }//GEN-LAST:event_registrarActionPerformed

    private void Repuesto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repuesto1MouseClicked
        // TODO add your handling code here:

        int fila = Repuesto1.getSelectedRow();

        if (fila != -1) {
            try {

                String codigo = String.valueOf(Repuesto1.getValueAt(fila, 0));
                String nombre = String.valueOf(Repuesto1.getValueAt(fila, 1));
                String cantidad = String.valueOf(Repuesto1.getValueAt(fila, 2));
                String categoria = String.valueOf(Repuesto1.getValueAt(fila, 3));
                String precio = String.valueOf(Repuesto1.getValueAt(fila, 4));

                String ganancia = String.valueOf(Repuesto1.getValueAt(fila, 5));
                String impuesto = String.valueOf(Repuesto1.getValueAt(fila, 6));
                String descripcion = String.valueOf(Repuesto1.getValueAt(fila, 7));

                String StockMin = String.valueOf(Repuesto1.getValueAt(fila, 8));

                String StockMax = String.valueOf(Repuesto1.getValueAt(fila, 9));

                int id = Integer.parseInt(codigo);
                int cant = Integer.parseInt(cantidad);
                float pre = Float.parseFloat(precio);
                float gan = Float.parseFloat(ganancia);
                float imp = Float.parseFloat(impuesto);
                int StMi = Integer.parseInt(StockMin);
                int StMa = Integer.parseInt(StockMax);

                jTextField1.setText(String.valueOf(id));
                jTextField2.setText(nombre);
                jTextField3.setText(String.valueOf(gan));
                jTextField6.setText(String.valueOf(cant));
                jTextField7.setText(String.valueOf(pre));
                jTextField8.setText(categoria);
                jTextField10.setText(String.valueOf(imp));
                jTextField9.setText(descripcion);
                jTextField4.setText(String.valueOf(StMi));
                jTextField5.setText(String.valueOf(StMa));

            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Error: El formato de los datos numéricos es incorrecto (Ej. 'precio' debe ser un número).",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "Ha ocurrido un error inesperado al cargar los datos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {

            JOptionPane.showMessageDialog(null,
                    "Por favor, seleccione una fila de la tabla para cargar los datos.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_Repuesto1MouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        modificar();
        limpiartabla();
        consulta();
        limpiarnuevo();

    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:

        eliminar();
        limpiartabla();
        consulta();


    }//GEN-LAST:event_eliminarActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        String CriterioBusqueda = this.jTextField2.getText().trim();

        DefaultTableModel ModeloObtenido = (DefaultTableModel) Repuesto1.getModel();

        TableRowSorter<DefaultTableModel> ordenador = new TableRowSorter<>(ModeloObtenido);

        Repuesto1.setRowSorter(ordenador);

        ordenador.setRowFilter(RowFilter.regexFilter(CriterioBusqueda, 1));

    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String CriterioBusqueda = this.jTextField1.getText().trim();

        DefaultTableModel ModeloObtenido = (DefaultTableModel) Repuesto1.getModel();

        TableRowSorter<DefaultTableModel> ordenador = new TableRowSorter<>(ModeloObtenido);

        Repuesto1.setRowSorter(ordenador);

        ordenador.setRowFilter(RowFilter.regexFilter(CriterioBusqueda, 0));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:

        limpiarnuevo();
    }//GEN-LAST:event_limpiarActionPerformed

    private void Repuesto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Repuesto1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Repuesto1MouseEntered

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {

            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {

            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Repuestos().setVisible(true));
    }

    void consulta() {
        String sql = "select * from repuestos";

        try {
            Connection con = DBConexion.conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] Repuestos = new Object[10];
            tabla = (DefaultTableModel) Repuesto1.getModel();

            while (rs.next()) {
                Repuestos[0] = rs.getInt("codigo");
                Repuestos[1] = rs.getString("nombre");
                Repuestos[2] = rs.getInt("cantidad");
                Repuestos[3] = rs.getString("categoria");
                Repuestos[4] = rs.getFloat("precio");
                Repuestos[5] = rs.getFloat("ganancia");
                Repuestos[6] = rs.getFloat("impuesto");
                Repuestos[7] = rs.getString("descripcion");
                Repuestos[8] = rs.getInt("stock_minimo");
                Repuestos[9] = rs.getInt("stock_maximo");

                tabla.addRow(Repuestos);

            }
            Repuesto1.setModel(tabla);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    void Registrar() {

    // 1. Get the values from the text fields
    String codigo = this.jTextField1.getText().trim();
    String nombre = this.jTextField2.getText().trim();
    String cantidad = this.jTextField6.getText().trim();
    String categoria = this.jTextField8.getText().trim();
    String precio = this.jTextField7.getText().trim();
    String ganancia = this.jTextField3.getText().trim();
    String impuesto = this.jTextField10.getText().trim();
    String descripcion = this.jTextField9.getText().trim();
    String StockMin = this.jTextField4.getText().trim();
    String StockMax = this.jTextField5.getText().trim();

    // Declaración de variables fuera del try/catch
    int cod, cant, Sto, StoM;
    float p, imp, gan;

    // 2. Validación de campos vacíos (incluyendo los de texto importantes)
    if (codigo.isEmpty() || nombre.isEmpty() || cantidad.isEmpty() || categoria.isEmpty()
            || precio.isEmpty() || ganancia.isEmpty() || impuesto.isEmpty() || StockMin.isEmpty()
            || StockMax.isEmpty()) {

        JOptionPane.showMessageDialog(null, "Todos los campos (Código, Nombre, Cantidad, Categoría, Precio, Ganancia, Impuesto, Stock Mínimo y Máximo) deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Conversión de tipos (Manejo de NumberFormatException)
    try {
        cod = Integer.parseInt(codigo);
        cant = Integer.parseInt(cantidad);
        p = Float.parseFloat(precio);
        gan = Float.parseFloat(ganancia);
        imp = Float.parseFloat(impuesto);
        Sto = Integer.parseInt(StockMin);
        StoM = Integer.parseInt(StockMax);
    } catch (NumberFormatException e) {
        // Mensaje de error ajustado para indicar que no todos los campos son enteros
        JOptionPane.showMessageDialog(null, "Verifique los campos numéricos (Código, Cantidad, Stock Mínimo/Máximo deben ser enteros; Precio, Ganancia, Impuesto pueden ser decimales).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Consulta SQL segura (USO DE PREPARED STATEMENT)
    String query = "INSERT INTO repuestos(codigo,nombre,cantidad,categoria,precio,ganancia,impuesto,descripcion,stock_minimo,stock_maximo) VALUES (?,?,?,?,?,?,?,?,?,?)";

    try {
        Connection con = DBConexion.conectar();
        PreparedStatement ps = con.prepareStatement(query);

        // Los valores se establecen a través del PreparedStatement
        ps.setInt(1, cod);
        ps.setString(2, nombre);
        ps.setInt(3, cant);
        ps.setString(4, categoria);
        ps.setFloat(5, p);
        ps.setFloat(6, gan);
        ps.setFloat(7, imp);
        ps.setString(8, descripcion);
        ps.setInt(9, Sto);
        ps.setInt(10, StoM);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Se ha registrado el repuesto con éxito.");
        limpiartabla();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(null, "Error al registrar en la base de datos: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        limpiartabla();
        consulta();
    }


    }

    void limpiartabla() {

        for (int i = 0; i < Repuesto1.getRowCount(); i++) {
            tabla.removeRow(i);

            i = i - 1;

        }

    }

    void modificar() {

        String codigoStr = this.jTextField1.getText();
        String nombre = this.jTextField2.getText();
        String cantidadStr = this.jTextField6.getText();
        String categoria = this.jTextField8.getText();
        String precioStr = this.jTextField7.getText();
        String gananciaStr = this.jTextField3.getText();
        String impuestoStr = this.jTextField10.getText();
        String descripcion = this.jTextField9.getText();
        String StockMinStr = this.jTextField4.getText();
        String StockMaxStr = this.jTextField5.getText();

        String query = "UPDATE repuestos SET nombre=?, cantidad=?, categoria=?, precio=?, ganancia=?, impuesto=?, descripcion=?, stock_minimo=?, stock_maximo=? WHERE codigo=?";

        try {

            int codigo = Integer.parseInt(codigoStr);
            int cantidad = Integer.parseInt(cantidadStr);
            float precio = Float.parseFloat(precioStr);
            float ganancia = Float.parseFloat(gananciaStr);
            float impuesto = Float.parseFloat(impuestoStr);
            int StockMin = Integer.parseInt(StockMinStr);
            int StockMax = Integer.parseInt(StockMaxStr);

            Connection con = DBConexion.conectar();
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, nombre);
            ps.setInt(2, cantidad);
            ps.setString(3, categoria);
            ps.setFloat(4, precio);
            ps.setFloat(5, ganancia);
            ps.setFloat(6, impuesto);
            ps.setString(7, descripcion);
            ps.setInt(8, StockMin);
            ps.setInt(9, StockMax);

            ps.setInt(10, codigo);

            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el código proporcionado");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Error de formato: Asegúrese de que todos los campos numéricos (código, cantidad, precios, stocks) contengan sólo números válidos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos: " + e.getMessage());
        }
    }

    void eliminar() {
        int fila = Repuesto1.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar.");
            limpiartabla();
            return;
        }

        try {
            int codigoAEliminar = Integer.parseInt(String.valueOf(Repuesto1.getValueAt(fila, 0)));

            Connection con = DBConexion.conectar();

            String Query = "DELETE FROM repuestos WHERE codigo = ?";
            PreparedStatement ps = con.prepareStatement(Query);

            ps.setInt(1, codigoAEliminar);

            int filasAfectadas = ps.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, "El respuesto con código " + codigoAEliminar + " ha sido eliminado.");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el repuesto con el código seleccionado.");
            }

            ps.close();
            con.close();

            limpiartabla();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Error interno: El código del repuesto no es un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
            e.printStackTrace();
        }

    }

    void limpiarnuevo() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Repuesto1;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JButton registrar;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
