package Formularios;

import static Clases.Respaldo.respaldo;
import static Clases.Restaurar.restaurar;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author WILLROSS
 */
public class Respaldo_BD extends javax.swing.JFrame {

    /**
     * Creates new form Restaurar
     */
    public Respaldo_BD() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Respaldo = new javax.swing.JTextField();
        Restauracion = new javax.swing.JTextField();
        respaldo = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        restaurar = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Respaldo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Respaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RespaldoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RespaldoKeyTyped(evt);
            }
        });
        jPanel1.add(Respaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 580, 40));

        Restauracion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Restauracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RestauracionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RestauracionKeyTyped(evt);
            }
        });
        jPanel1.add(Restauracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 580, 40));

        respaldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        respaldo.setText("GUARDAR ");
        respaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respaldoActionPerformed(evt);
            }
        });
        jPanel1.add(respaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 150, -1));

        abrir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abrir.png"))); // NOI18N
        abrir.setText("Abrir Archivo SQL");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jPanel1.add(abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 210, -1));

        restaurar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        restaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurar.png"))); // NOI18N
        restaurar.setText("RESTAURAR");
        restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarActionPerformed(evt);
            }
        });
        jPanel1.add(restaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 160, -1));

        seleccionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seleccionar.png"))); // NOI18N
        seleccionar.setText("Seleccionar Ubicacion");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RESPALDO Y RESTAURACION");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESPALDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESTAURACION");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RestauracionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RestauracionKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_RestauracionKeyReleased

    private void RestauracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RestauracionKeyTyped

    }//GEN-LAST:event_RestauracionKeyTyped

    private void respaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respaldoActionPerformed
        final String ruta = Respaldo.getText();

        if (ruta.trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione una ubicación y nombre respaldar",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        try {
            respaldo.setEnabled(false);
            new Thread(() -> {
                respaldo(ruta);
                SwingUtilities.invokeLater(() -> {
                    Respaldo.setText("");
                    respaldo.setEnabled(true);
                });
            }).start();
        } catch (Exception ex) {
            System.out.println("Error al iniciar el proceso de respaldo: " + ex.getMessage());
            SwingUtilities.invokeLater(() -> {
                respaldo.setEnabled(true);
            });
        }
    }//GEN-LAST:event_respaldoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new java.io.File(Restauracion.getText()));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Seleccionar Archivo SQL");
        int userSelection = fileChooser.showOpenDialog(Respaldo_BD.this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToOpen = fileChooser.getSelectedFile();
            String path = fileToOpen.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".sql")) {
                JOptionPane.showMessageDialog(Respaldo_BD.this,
                        "Por favor, selecciona un archivo con extensión .sql",
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Restauracion.setText(path);
        }


    }//GEN-LAST:event_abrirActionPerformed

    private void restaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarActionPerformed
        final String archivo = Restauracion.getText();
        if (archivo.trim().isEmpty() || !new File(archivo).exists()) {
            JOptionPane.showMessageDialog(Respaldo_BD.this, "Selecciona un archivo SQL.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SwingUtilities.invokeLater(() -> {
            try {
                restaurar.setEnabled(false);
                new Thread(() -> {
                    restaurar(archivo);
                    SwingUtilities.invokeLater(() -> {
                        restaurar.setEnabled(true);
                        Restauracion.setText("");
                    });
                }).start();
            } catch (Exception ex) {
                System.out.println("Error al iniciar la restauración: " + ex.getMessage());
                SwingUtilities.invokeLater(() -> {
                    restaurar.setEnabled(true);
                    Restauracion.setText("");
                    JOptionPane.showMessageDialog(Respaldo_BD.this,
                            "Error al iniciar el proceso: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                });
            }
        });
    }//GEN-LAST:event_restaurarActionPerformed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Guardar Respaldo");
        int userSelection = fileChooser.showSaveDialog(Respaldo_BD.this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            String path = fileToSave.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".sql")) {
                path += ".sql";
            }
            Respaldo.setText(path);
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed

        Menu m = new Menu();
        m.show();
        dispose();

    }//GEN-LAST:event_regresarActionPerformed

    private void RespaldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespaldoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_RespaldoKeyReleased

    private void RespaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespaldoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_RespaldoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respaldo_BD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respaldo_BD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respaldo_BD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respaldo_BD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respaldo_BD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Respaldo;
    private javax.swing.JTextField Restauracion;
    private javax.swing.JButton abrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar;
    private javax.swing.JButton respaldo;
    private javax.swing.JButton restaurar;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
